# Generated by Django 5.2.5 on 2025-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_alter_room_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(default="Lviv", max_length=255),
            preserve_default=False,
        ),
    ]
