# Generated by Django 5.2.5 on 2025-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('hotel', '0002_alter_hotel_description_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='service_booking', to='hotel.service'),
        ),
    ]
