# Generated by Django 5.2.5 on 2025-08-14 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 19, 14, 53, 847589)),
        ),
    ]
