# Generated by Django 5.2.5 on 2025-08-16 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 16, 13, 48, 33, 631735)
            ),
        ),
    ]
