# Generated by Django 5.2.5 on 2025-08-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='uptated_at',
            new_name='updated_at',
        ),
    ]
